apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jenkins-ns
  name: deployment-2048
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-2048
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-2048
    spec:
      containers:
      - image: mahaelkomey/jenkins-2
        imagePullPolicy: Always
        name: app-2048
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /var/run/
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/