apiVersion: v1
kind: Service
metadata:
  namespace: jenkins-ns
  name: jenkins-loadbalancer
spec:
  selector:
    app.kubernetes.io/name: app-2048
  ports:
    - name: lb-port
      protocol: TCP 
      port: 80
      targetPort: 8080
  type: LoadBalancer