#install aws cli 

  - name: ping
    ping:

  - name: update
    package:
      update_cache: true
      
  - name: Install package dependencies.
    package: name={{ item }} state=present
    with_items:
      - unzip

  - name: dounload awscli 
    ansible.builtin.command: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

  - name: unzip awscli
    ansible.builtin.command: unzip awscliv2.zip

  - name: run the awscli file
    ansible.builtin.command: ./aws/install
    
  - name: Configure AWS
    shell: aws configure set {{ item.key }} {{ item.value }} --profile {{ aws_profile }}
    with_dict:
      aws_access_key_id: "{{ aws_access_key }}"
      aws_secret_access_key: "{{ aws_secret_key }}"
      region: "{{ aws_region }}"
      format: "{{ aws_format }}"
    become_user: "{{ aws_system_user }}"
    changed_when: false