#deploy namespace
  - name: Create a k8s namespace
    k8s:
      name: jenkins-ns
      api_version: v1
      kind: Namespace
      state: present
        
#deploy jenkins  
  - name: deploy jenkins
    k8s:
      state: present
      src: jenkins-deploy-2.yaml
      
#deploy jenkins loadbalancer 
  - name: deploy jenkins loadbalancer
    k8s:
      state: present
      src: jenkins-loadbalancer.yaml
      
- name: Configure AWS.
    shell: aws configure
    with_dict:
      aws_access_key_id: "{{ aws_access_key }}"
      aws_secret_access_key: "{{ aws_secret_key }}"
      region: "{{ aws_region }}"
      format: "{{ aws_format }}"
    become_user: "{{ aws_system_user }}"
    changed_when: false
