#configaure the ec2 as slave
  - name: Creates directory
    file:
      path: slave
      state: directory
      
  - name: update
    package:
      update_cache: true
      
  - name: update
    apt:
      name: openjdk-11-jdk
      update_cache: true